### ISSUE TITLE
 [warn]: #0 Template received after missing 516 packets host=["AF_INET", 50101, "x.x.x.x", "x.x.x.x"] source_id=524544 flowset_id=320

### ISSUE THREAD

**Issue by gerrylon** [yvesbd/fluent-plugin-netflowipfix#2]

**Comment by yvesbd** [comment]
This is expected behaviour, and something I should likely document. NetFlow v9 or IPfix (v10) traffic is template based, meaning that this until we have a template we do not know what fields are stored. Templates are generally sent every minute, but this is a network device parameter. This warning is just a notification that the number of packets (potentially with multiple flows) were received prior. It is normal when restarting the service, but may be an issue if occuring later during processing.

**Comment by gerrylon** [comment]
Parsed result for ipfix flow was like:
```
{
...
    "flowStartSysUpTime": 2566,
    "flowEndSysUpTime": 11222785,
    "host": [
      "AF_INET",
      4739,
      "10.1.23.11",
      "10.1.23.11"
    ],
...
}
```

the host value should be like: "10.1.23.11", not an array?
